import type { Metadata } from "next";

import "./globals.css";
import Navbar from "../components/shared/Navbar";
import Footer from "../components/Footer";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Next Auth",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body>
        <Navbar />
        <div className="min-h-screen w-[100%] mx-auto">
          {children}
          <Toaster />
        </div>
        <Footer />
      </body>
    </html>
  );
}
